### USERS POST
POST localhost:8080/user
content-type:application/json

{
  "login" : "bear",
  "password" : "123"
}

### USERS POST
POST localhost:8080/user
content-type:application/json

{
  "login" : "fox",
  "password" : "1234"
}

###
GET localhost:8080/user/bear/123

###
GET localhost:8080/user/1


###
GET localhost:8080/user

### POST MESSAGE
POST localhost:8080/sse/message/1
content-type:application/json

{
  "message" : "Awesome"
}


